-- Create table
create table LDCUSTOMERADDRESS
(
  LDCUSTOMERNO                VARCHAR2(100) not null,
  CIFID                       VARCHAR2(100) not null,
  RESIDENTIALADDRESSTYPE      VARCHAR2(100),
  RESIDENTIALPROVINCE         VARCHAR2(100),
  RESIDENTIALCITY             VARCHAR2(100),
  RESIDENTIALDISTRICT         VARCHAR2(100),
  RESIDENTIALDETAILEDADDRESS  VARCHAR2(100),
  RESIDENTIALPOSTCODE         VARCHAR2(100),
  CONTACTADDRESSTYPE          VARCHAR2(100),
  CONTACTPROVINCE             VARCHAR2(100),
  CONTACTCITY                 VARCHAR2(100),
  CONTACTDISTRICT             VARCHAR2(100),
  CONTACTDETAILEDADDRESS      VARCHAR2(100),
  CONTACTPOSTCODE             VARCHAR2(100),
  HOMEADDRESSTYPE             VARCHAR2(100),
  HOMEPROVINCE                VARCHAR2(100),
  HOMECITY                    VARCHAR2(100),
  HOMEDISTRICT                VARCHAR2(100),
  HOMEDETAILEDADDRESS         VARCHAR2(100),
  HOMEPOSTCODE                VARCHAR2(100),
  PERMANENTADDRESSTYPE        VARCHAR2(100),
  PERMANENTPROVINCE           VARCHAR2(100),
  PERMANENTCITY               VARCHAR2(100),
  PERMANENTDISTRICT           VARCHAR2(100),
  PERMANENTDETAILEDADDRESS    VARCHAR2(100),
  PERMANENTPOSTCODE           VARCHAR2(100),
  PREVIOUADDRESSTYPE          VARCHAR2(100),
  PREVIOUPROVINCE             VARCHAR2(100),
  PREVIOUCITY                 VARCHAR2(100),
  PREVIOUDISTRICT             VARCHAR2(100),
  PREVIOUDETAILEDADDRESS      VARCHAR2(100),
  PREVIOUPOSTCODE             VARCHAR2(100),
  PREVIOUCOMPANY              VARCHAR2(100),
  PREVIOUCOMPANYADDRESS       VARCHAR2(100),
  PREVIOUPOSITION             VARCHAR2(100),
  PREVIOUINDUSTRYTYPE         VARCHAR2(100),
  PREVIOUOCCUPATION           VARCHAR2(100),
  PREVIOUEMAILADDRESS         VARCHAR2(100),
  PREVIOUINCOME               VARCHAR2(100),
  PREVIOUMARITALSTATUS        VARCHAR2(100),
  PREVIOUHEIGHT               VARCHAR2(100),
  PREVIOUWEIGHT               VARCHAR2(100),
  PREVIOUINCOMESOURCE         VARCHAR2(100),
  PREVIOUWEALTHSOURCE         VARCHAR2(100),
  PREVIOUTELEPHONESOURCE      VARCHAR2(100),
  PREVIOUHEALTHCARE           VARCHAR2(100),
  PREVIOUFAMILYINCOME         VARCHAR2(100),
  ERESIDENTIALADDRESSTYPE     VARCHAR2(100),
  ERESIDENTIALPROVINCE        VARCHAR2(100),
  ERESIDENTIALCITY            VARCHAR2(100),
  ERESIDENTIALDISTRICT        VARCHAR2(100),
  ERESIDENTIALDETAILEDADDRESS VARCHAR2(100),
  COMPANYADDRESS1             VARCHAR2(100),
  COMPANYADDRESS5             VARCHAR2(100),
  COMPANYADDRESS4             VARCHAR2(100),
  COMPANYADDRESS3             VARCHAR2(100),
  COMPANYADDRESS2             VARCHAR2(100),
  WORKADDRESSTYPE             VARCHAR2(100),
  WORKCITY                    VARCHAR2(100),
  WORKPROVINCE                VARCHAR2(100),
  WORKPOSITION                VARCHAR2(100),
  WORKDETAILEDADDRESS         VARCHAR2(100),
  WORKDISTRICT                VARCHAR2(100),
  OCCUPATION                  VARCHAR2(100),
  INDUSTRYTYPE                VARCHAR2(100),
  INCOME                      VARCHAR2(100),
  EMAILADDRESS                VARCHAR2(100),
  FAMILYINCOME                VARCHAR2(100),
  ECONTACTADDRESSTYPE         VARCHAR2(100),
  ECONTACTPROVINCE            VARCHAR2(100),
  ECONTACTCITY                VARCHAR2(100),
  ECONTACTDISTRICT            VARCHAR2(100),
  ECONTACTDETAILEDADDRESS     VARCHAR2(100),
  EHOMEADDRESSTYPE            VARCHAR2(100),
  EHOMEPROVINCE               VARCHAR2(100),
  EHOMECITY                   VARCHAR2(100),
  EHOMEDISTRICT               VARCHAR2(100),
  EHOMEDETAILEDADDRESS        VARCHAR2(100),
  EPERMANENTADDRESSTYPE       VARCHAR2(100),
  EPERMANENTPROVINCE          VARCHAR2(100),
  EPERMANENTCITY              VARCHAR2(100),
  EPERMANENTDISTRICT          VARCHAR2(100),
  EPERMANENTDETAILEDADDRESS   VARCHAR2(100),
  EPREVIOUADDRESSTYPE         VARCHAR2(100),
  EPREVIOUPROVINCE            VARCHAR2(100),
  EPREVIOUCITY                VARCHAR2(100),
  EPREVIOUDISTRICT            VARCHAR2(100),
  EPREVIOUDETAILEDADDRESS     VARCHAR2(100),
  POSTALFLAG                  VARCHAR2(10)
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 16
    next 8
    minextents 1
    maxextents unlimited
  );
-- Add comments to the columns 
comment on column LDCUSTOMERADDRESS.OCCUPATION
  is '职业代码Occ Code';
comment on column LDCUSTOMERADDRESS.INDUSTRYTYPE
  is '行业类型';
comment on column LDCUSTOMERADDRESS.INCOME
  is '收入';
comment on column LDCUSTOMERADDRESS.EMAILADDRESS
  is '邮箱地址';
comment on column LDCUSTOMERADDRESS.FAMILYINCOME
  is '家庭收入';
-- Create/Recreate primary, unique and foreign key constraints 
alter table LDCUSTOMERADDRESS
  add constraint CCC primary key (CIFID)
  using index 
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
